### ISSUE TITLE
Highlightin 

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#101]
Time: 09.54
Device: Surface Pro 4
Project Code: 3133
Project Key: oi8hz

I highlighted some text on page 9
![image](https://cloud.githubusercontent.com/assets/25382402/22729855/ce14b688-ede4-11e6-95b6-2ebf89e3d471.png)

The highlighted part appears on page 10 too
![image](https://cloud.githubusercontent.com/assets/25382402/22729881/e086ea02-ede4-11e6-8da5-022dccce7421.png)

**Comment by corradocavalli** [comment]
This is a longtime bug affecting CollaBoard, luckily this time was reproducible and it should be fixed now, also PDF loafing performance have been slightly improved.
@mtg1986 @agorog @teguria Inking engine has been refactored to be more reactive so I invite you to do several inking tests  with all kind of tiles (engine is shared) so that we are sure no regression bugs have been introduced. Thanks
