### ISSUE TITLE
Upload PDF brochure style

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#107]
1.Upload PDF in Brochure Style 
2.Go from page 1 to 2, to 3, to 4 and so on
Not all pages are shown in the PDF tile. 

To reproduce, use the attached pdf. 

[BROCHURE-WEB.pdf](https://github.com/IBVSoftware/CollaBoard-Feedback/files/770250/BROCHURE-WEB.pdf)

**Comment by agorog** [comment]
1 page is A4, page 2-6 are A3, i.e. there is page format change after page 1 and after page 6. Page 7 is A4 again.

**Comment by corradocavalli** [comment]
The original implementation was using the 1st page to calculate tile dimensions, since this is a mized mode PDF (A4+A3) A3 pages where cut. We now check all the pages using the largest one to as reference for tile dimension calculation. Se result below. Please tri it when new release will be out.
![tilepdf](https://cloud.githubusercontent.com/assets/5617938/22879110/c249dc38-f1dc-11e6-9f7b-ecc2aeeedaa7.gif)

**Comment by mtg1986** [comment]
Tested with 1.3.52

A3 Pages look now good. From the first and the last page (A4) some content is cutted away.
