### ISSUE TITLE
Taking picture from video

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#140]
If i try to take a picture from a video with ink, ink isn't reported on the image

**Comment by gsantopaolo** [comment]
@corradocavalli  any news?

**Comment by corradocavalli** [comment]
This is by design at the moment, we use mediacapture.CapturePhotoToStreamAsync API that doesn't inlcude's ink overlay. 
Alternatives: 
-Grab client area: Includeds ink but with poor quality being part of jpeg
-Copy strokes to copied image, but we need to consider that generated tile has a different size because it comes straight from video.
