### ISSUE TITLE
Unable to register an evaluation version

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#149]
I did a demo to a reseller. Reseller downloaded the app from the Store. He logged in with his Office 365 account. He went through the registration process and he got this error message (in attach) @corradocavalli @gsantopaolo 
![error](https://cloud.githubusercontent.com/assets/19929395/23747580/823c831a-04c0-11e7-9169-d927ccb5d9bf.jpg)

**Comment by gsantopaolo** [comment]
@teguria we already discussed this and already provided you a solution. This is already fixed in Dev environment, with the next production version will also be publicly fixed.
As already told you, at the moment, when this happens, user needs at last to create or join a project before trying to request the license.
If after joining or creating a project he try to request or add a license key it will work as a charm, thank you
