### ISSUE TITLE
URGENT object must preserve status arcoross lifetime and service calls

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#157]
This is very important: I discovered that if an object is deleted and the tile is moved while deleting it happens:
1. Delete sends azureblostatus delete
2. move tile sends Update with azureblobstatus onazure 

Now, the point is first of all I want you to explain me how is possible that you are loosing this vital information, then please keep in mind that in such application to be successful and not adding bugs that is near impossible to discover preserve object status during its life time and while sending calls to server is mandatory.
I can accept a junior making such mistake not a senior.

We must discus this face by face and i want you to explain me why we are loosing this crucial information.
I've found now this issue on the azureblobstatus but now i'm afraid any other object properties can be affected as well.

This is really bad.

**Comment by corradocavalli** [comment]
The move to the new delete infrastructure has been introduced without deep testing and immediately passed to testing people because we had to test. Having issues it's inevitable in these pressure conditions.
If I well understood the scenario is that you get un update after the tile is deleted and i think this happens if you move very quickly the tile after pressing the delete button (the tile should vanish nearly instantly after delete button is pressed and I'd like to know better what 'while the tile is deleting' means)

AzureBlobStatus=OnAzure sounds to me like the default value for the enum but I have to check the code, since property is not nullable you should expect at least default value to be sent with every call.
Feel free to call me tomorrow late morning so that we can discuss better this if you want.

On 14 Mar 2017, at 14:15, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


This is very important: I discovered that if an object is deleted and the tile is moved while deleting it happens:

  1.  Delete sends azureblostatus delete
  2.  move tile sends Update with azureblobstatus onazure

Now, the point is first of all I want you to explain me how is possible that you are loosing this vital information, then please keep in mind that in such application to be successful and not adding bugs that is near impossible to discover preserve object status during its life time and while sending calls to server is mandatory.
I can accept a junior making such mistake not a senior.

We must discus this face by face and i want you to explain me why we are loosing this crucial information.
I've found now this issue on the azureblobstatus but now i'm afraid any other object properties can be affected as well.

This is really bad.

**Comment by gsantopaolo** [comment]
@corradocavalli  21 days are passed I need an update on this, thanks
