### ISSUE TITLE
Multiink on single sticky on Hub

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#198]
Version 1.3.59.0
Project Code: 670
Project Key: kelpr 
Device : Hub
DB: prod 

Inking on one sticky note, doing different actions recording on video which will be uploaded by Tamara.

**Comment by tamarawasser** [comment]
https://ibvinfo.sharepoint.com/sites/mktg/_layouts/15/guestaccess.aspx?guestaccesstoken=jK%2f39yzsf1HTZ44f7B806X3bJVDW61YA%2byQWJB1j%2brA%3d&folderid=2_136f56f9a16e6404da6dd80b54c8c783d&rev=1

**Comment by gsantopaolo** [comment]
Hello Andreas and thank you for your videos.
Maybe there is some misunderstood btw I'm quite sure I've warned you and the crew that this is by design.
If two stylus will start at the exact same time to ink then we will not be able to set StrokeAttributes of one of the pen. This is because of the InkCanvas architecture. 
The way to overcome to this *little* bug is to switch to native / directx implementation of a big piece of development.
if you want to go that way please let me know, we have to talk about budget and timings otherwise please feel free to close this.
thank you
-g

**Comment by agorog** [comment]
Version 1.3.60.0: Lasso fixed

**Comment by agorog** [comment]
Version 1.3.60.0: I cant ink one sticky and lasso on another sticky. I assume this is the same reported in #197 inking on 2 sticky. So we close this issue.
