### ISSUE TITLE
CB ends after Device goes to sleep/suspend mode

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#208]
Version 1.3.61.0 
Devices: all

Device left with CollaBoard open, coming back after sometime, CollaBoard ended itself. 
We had this bug several weeks ago, is now back again.

**Comment by corradocavalli** [comment]
Is device went to sleep? What happens if you put device in sleep mode manually? Can you tell us what is your machine id? (Via info)

On 12 Apr 2017, at 08:39, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Version 1.3.61.0
Devices: all

Device left with CollaBoard open, coming back after sometime, CollaBoard ended itself.
We had this bug several weeks ago, is now back again.

**Comment by agorog** [comment]
Here is the machine id of the hub: 
![whiteboard_2017-04-12_092227](https://cloud.githubusercontent.com/assets/19590642/24948920/31f8b7f4-1f6c-11e7-8add-0a7c9af13cfd.png)

**Comment by agorog** [comment]
Machine ID of Notebook where this happened today between 10:30 and 11:00 
![grafik](https://cloud.githubusercontent.com/assets/19590642/24950214/8c8078ca-1f70-11e7-9b0d-fa348b7a21c5.png)

**Comment by corradocavalli** [comment]
It should be fixed in build 62, to be clear, this issue is totally unrelated to the suspend/resume issue we had several weeks ago, Please try it and give us feedback.

**Comment by agorog** [comment]
Fixed with Version 62
