### ISSUE TITLE
Paste to image - Size Wrong

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#213]
![image](https://cloud.githubusercontent.com/assets/19570958/25004403/85f8e62e-2054-11e7-880b-126d08382c69.png)

1.Copy lassoed Ink on a sticky note
2.Paste over Radial menu -->Then the size of the pasted ink is wrong

**Comment by mtg1986** [comment]
When Inking now in a pasted ink (copied with the lasso from a sticky note), the stroke is very large. It seems that there is a re-sizing problem, when copying ink from a sticky note and paste it to the board (as it becomes its own tile)

**Comment by corradocavalli** [comment]
This is by design, to give you an example:
Tile 1: is a 1000x1000 image that we resize down to min tile size of 450x450
Tile 2: is a 500x500 image that we scale down to min size of 450x450.
While they look the same if you lasso tile's 1 entire area it will be 1000x1000 wide and if you paste it on 2nd tile it won't necessarily fit.
you can try loading the same picture on two tiles, don't resize them and in this case ink will match.

**Comment by gsantopaolo** [comment]
@mtg1986  @corradocavalli  any update on this?

**Comment by mtg1986** [comment]
I tested: 

Ink on Sticky Note 
Copied Ink to Map Image (Ink on the map Image)
Copied Ink ton canvas (Ink on the canvas) 

-->When Inking after copying, then the Ink is now the same size as of the copied ink. I think we can close that.
