### ISSUE TITLE
Cortana to recognize single letters for loading projects

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#220]
Right now Cortana tries to convert speech into words.
When loading a project, Cortana should just spell the single letters and turns spelled letters into letters

**Comment by corradocavalli** [comment]
Please check again when a new version will be available, if not, check machine's Cortana configuration since it works as expected on my machine.
The example below shows me saying "one two three four" and "six double b"
![image](https://cloud.githubusercontent.com/assets/5617938/25389400/c6254ca8-29d0-11e7-94b1-877c47ba65fb.png)

**Comment by mtg1986** [comment]
Workes fine with 1.3.82
Tested: 04.05.2017
