### ISSUE TITLE
Multiuser unable to work together 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#230]
Version 81
Project 6842 
Date 2.5.2017 14:20- 38 
Machine ID:  f07af071-1541-1de0-5297-41f24db959e8

We had several problems working on one Hub and 5 devices. 

- After loading mutliple photos the screen goes black, you see only the mouse, then you see collaboard again, then goes to black again, seems to be something is looping. After a certain time a message was displayed, that a files exceeded 10MB (this is true) but then the whole system looped. Everthing went slow it was nearly unpossible to work in any other app. I had to reboot the surface. 

After reboot loading the project needed several minutes to load but whole system and other applications slowed completly down. After project was loaded it was shown then screen went black only showing Mousecursor then tiles wer displayed again and then again black screen and so on. Had to cancel CollaBoard using Task Manager. 

Similar behavîour on the other machines, i.e. people were blocked and coldn't do anything. 

We stopped testing now.

**Comment by corradocavalli** [comment]
@agorog  Can you send us the project key via mail?

**Comment by corradocavalli** [comment]
@agorog @mtg1986 @teguria We have analyzed the project you indicated and we have some considerations about it:
The project is made up of nearly 100 tiles, for a total of nearly 90 MB of files and you have uploaded many pictures that are 5000x5000 pixels wide. 
This of course stresses too much the graphic card, that's why you see the screen blinking (BTW: on our machines with pro graphic cards doesn't happen) 
I already told you during last testing days that **this is not a scenario we support yet** since images are not optimized so please test the build **using real-world scenarios**. 
While we agree that work load has to be improved we need to test scenarios that are close to ones our customers are using in a daily basis first while also working also on optimizations side.

**Comment by gsantopaolo** [comment]
Just fyi, i a very future implementation we are going to resize images in terms of pixels and bytes so you won't experience such scenario any more.... 
Please, as already requested we need some more test of this version so we can push it out... by dropping all that files at the moment is useless...
thank you
-g

**Comment by corradocavalli** [comment]
In build 82 you will have image optimization, project 6842 image size slimmed down from about 70 MB to 5.5 MB.
The same project now runs fluid on my Surface Pro 3.

**Comment by agorog** [comment]
ok, can you publish 82 as beta in store. We didn't do anything other then with earlier texts, so it seems that there was some change with image processing compared with the versions we tested before. I agree that copy/posting (was not dropping, but copy/paste thru explorer) all that images from multiple users is not a realistic scenario, so we have to change the test scenario. However the loading of a project should work smoothly with many images, as this was the case before.

**Comment by gsantopaolo** [comment]
Sorry @agorog but also before we skipped any tests including 100+ image tiles 5000x5000 pixel.
Our internal roadmap has already changed because of your request! :(

**Comment by gsantopaolo** [comment]
@corradocavalli  from now on until i'll be back. Please only follow the feature timeline you will get. Any other change has to be approved by me.

thanks all for understanding

**Comment by agorog** [comment]
Fixed with 82
