### ISSUE TITLE
UI Question - Set background Image vs. Background Color

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#286]
I was asked, why do I adjust the background Color under the menu item "Settings" and why do I set the background image under the menu item "Info"

**Comment by corradocavalli** [comment]
Because former is app based while latter is project based.

On 21 Aug 2017, at 10:05, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


I was asked, why do I adjust the background Color under the menu item "Settings" and why do I set the background image under the menu item "Info"
