### ISSUE TITLE
Tile Rotation - Enabeling and Disabeling

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#300]
In earlier version we had the baviour, when we rotated tiles and disabled tile rotation all tiles moved back automatically to horizontal orientation. 

It this on purpose that we do not have this anymore?

**Comment by gsantopaolo** [comment]
Id do not think so, anyway no one asked me to change this behavior, so any changes wasn't approved!

**Comment by corradocavalli** [comment]
I didn't changed this on purpose, so it might be the result of recent changes.

On 4 Sep 2017, at 10:16, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #300<https://github.com/IBVSoftware/CollaBoard-Feedback/issues/300> to @corradocavalli<https://github.com/corradocavalli>.

**Comment by corradocavalli** [comment]
I had a look at commit stack and this has effectively changed because previous behavior was conceptually wrong.
Tile Rotation is an **app** setting, this means that each installation can have it's own value.
Tile Rotation means:  "_app cannot be rotated, not tile cannot have a rotation angle != 0_" this means that an app having rotation=false can also load projects containing rotated tiles.
In previous build a user setting this setting to false in it's app was causing all project tiles to reset it's angle even for those users having their setting set to true.
Now feature does what it states: It prevent the rotation of the tiles for those app whose setting is false.

**Comment by gsantopaolo** [comment]
you both are right, let me think about it

**Comment by gsantopaolo** [comment]
duplicate with #244

**Comment by gsantopaolo** [comment]
This is something that we have to improve... maybe by adding some global project settings

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
