### ISSUE TITLE
Got panda after leaving collabord on hide for a wile

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#309]
On my Surface Pro i switched to some different application for a wile, when back on collaboard, i got the pada "An initialization exception occurred, all functionalities are unavailable. Application will be now closed"

04/09/2017 21.30 project id 7817

**Comment by corradocavalli** [comment]
This happens because sometimes signal R doesn't reconnect within X (configurable) number of seconds.
Technically the app handles it, asking user to relaunch app, what else can we do?

On 4 Sep 2017, at 15:33, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #309<https://github.com/IBVSoftware/CollaBoard-Feedback/issues/309> to @corradocavalli<https://github.com/corradocavalli>.

**Comment by gsantopaolo** [comment]
I don't think this is the issue, we have to test together, try to reproduce, and then find a better solution

**Comment by corradocavalli** [comment]
I double checked: That message is displayed only when SignalR initialization fails (we force application closing because any other action can't be performed) application on resume it initializes Signal R engine and waits up to 5 seconds for HubService status to be "Connected" if after 5 seconds status is not "Connected" that message appears.
As safety guard I've added a small delay between resume event and Signal R initialization process, apart that I don't have any idea about a possible fix of this.

**Comment by corradocavalli** [comment]
If that is the exact message there are no other conditions that makes it appear. Let's try to reproduce it next week anyway.

**Comment by gsantopaolo** [comment]
Too old, closing
