### ISSUE TITLE
Server side notification errors must be as descriptive as possible

### ISSUE THREAD

**Issue by corradocavalli** [IBVSoftware/CollaBoard-Feedback#313]
The information returned by Notification Hub errors must be as as descriptive as possible, the current information make discovering the reason of the issue very hard.
Since issues also happens quite randomly with actual description is nearly impossible to detect what might be the action that caused the problem.

Please also note that SignalR aren't 100% guaranteed to be received in the same exact sequence, so i think that if a message requires to perform an action that is not causing any project sync issue (e.g Unlocking a tile that is already Unlocked) it should just ignore it.

**Comment by gsantopaolo** [comment]
@corradocavalli  hard work to do for the whole service layer.
Please:
1. Verify witch service calls / signalr methods are more relevant for you
2. don't know if i got well you comment on signalr, need to discuss

**Comment by gsantopaolo** [comment]
Ok, I dig into service code and I believe the most important part you are referring to is the signalr one.
Now first of all let's distinguish something.:
Code running at the moment on signalr was throwing to the client the same exact error i was getting, btw i believe that you issues are generate where no real exception was thrown but when a logic exception was generating it: when, for example you are asking to update a tile that i do not find the id i just throw back a dbfailedtoperforexception without any message.
now i changed the code so that more than the exception itself you are also getting a message.

On signalR now the code looks like this
![image](https://user-images.githubusercontent.com/9937149/30186717-02011462-9427-11e7-8859-cc36226c4352.png)

Let me know if this helps

**Comment by corradocavalli** [comment]
Yes, i think that errors are mostly related to SignalR messages and they're due to operation inconsistency like you said.
My experience is that **PostLock/Unlock/Updated** are the most frequent cause of this exception and these are the most intensive message interchanged between client and server and my doubt is that inconsistency might come from lost SignalR messages or messages coming in different order to the server.
Maybe we should consider using a more relaxed behavior for this messages when they lend to a non critical state (like asking to unlock a tile that is already unlocked)

**Comment by corradocavalli** [comment]
Much better now, thanks.

**Comment by gsantopaolo** [comment]
New signalr services are already on dev. 
All signalrmethods now have a description for errors in all cases

About relaxed behavior, we used it in past and they wasn't good, we had lots of sync problem

**Comment by corradocavalli** [comment]
Message is more descriptive now, be sure that info is also logged into telemetry.
