### ISSUE TITLE
C-Scaler Proxy Issue on Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#316]
A company is using the C-Scaler Proxy on its Surface Hub. They can access the internet over the browser but they cannot get an internet-connection with CollaBoard. 
This could be something that will be solved with Fall-Update of Win10, but we are not sure. 

Although this is maybe a Sysadmin task, who would need to figure out how to configure the proxy, I will add requests like that to GitHub to. Let me know if we should do it differently.

**Comment by corradocavalli** [comment]
@mtg1986 No idea what C-Scaler proxy is, but be aware that in order to start CollaBoard must be able to reach www.microsoft.com domain otherwise connection is reported as failed.

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli  in the next development we have a new functionality for being developed that will check only ibv-solutions.com.

At the moment you can tell customer that domains: 

- www.microsoft.com port 80 
- *.ibv-solutions.com port 443 (https) 

needs to be reachable in order for CollaBoard to work

In the near future we will only need *.ibv-solutions.com port 443 (https)  to be reachable for collaboard to work.

thank you
-g

**Comment by mtg1986** [comment]
@gsantopaolo : Please make sure to take ibvsolutions.com as we will shut down ibv-soltuions.com in the next weeks.
Thanks
Michael

**Comment by corradocavalli** [comment]
Let's be sure that domain will be 100% reachable otherwise all Collaboard installations won't launch :-)

On 10 Sep 2017, at 09:03, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


@gsantopaolo<https://github.com/gsantopaolo> : Please make sure to take ibvsolutions.com<http://ibvsolutions.com> as we will shut down ibv-soltuions.com<http://ibv-soltuions.com> in the next weeks.
Thanks
Michael

**Comment by gsantopaolo** [comment]
Closing, too old. It has to be fixed in version 2.0+ at last cb should give a more descriptive error out, like ask certificate issue
