### ISSUE TITLE
Giving ownership from someone to someone to someone

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#329]
v. 108
- I set the project to read-only
- I gave ownership to another person
- the person got a message that he was the owner
- he clicked on Yes
- He wasn't kicked out of the project, instead he got the message attached
![collaboard error](https://user-images.githubusercontent.com/19929395/30317072-5a65fec6-97a9-11e7-8e5a-b1d42c442f09.png)

**Comment by corradocavalli** [comment]
This might be a conseguence of #328, please try again without changing project to read-only. Also note that there's a pending bug #288 related to change of ownership.

**Comment by corradocavalli** [comment]
Tested agains and it works, closing.

**Comment by gsantopaolo** [comment]
do not understand why closed. was it fixed?

**Comment by corradocavalli** [comment]
Yes, we tested it and it was fixed, issue was caused because Ale changed the project to read-only and it introduced another bug that we have to fix.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Gian Paolo Santopaolo<mailto:notifications@github.com>
Inviato: martedì 12 settembre 2017 17:51
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Corrado Cavalli<mailto:corrado@outlook.com>; State change<mailto:state_change@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Giving ownership from someone to someone to someone (#329)


do not understand why closed. was it fixed?
