### ISSUE TITLE
CollaBoard Version verified does not work as expected

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#354]
If on the server and higher version is configured than the one on the client.
At the moment noting happens until i try to load a project or create a new one
If i try to load a project i got a very bad behavior, service returns the correct error code but in the panel i got this 
![image](https://user-images.githubusercontent.com/9937149/30523279-04527b06-9bdf-11e7-9c8f-d6aafa94476a.png)
Not really telling me what the error is.
If i try to create a new project I got this 
![image](https://user-images.githubusercontent.com/9937149/30523287-2a9f0bf8-9bdf-11e7-8dd7-2cbc0ac6d5f6.png)

I can accept the second but current behavior **MUST** be:
At a very early point in the app life-cycle, such us when the app is showing the first welcome screen (either if it is the login or only the welcome) version + licensing must be checked, then nothing else has to be permitted to the user if error code is 13.

In previous version we got a popup saying that client needs to be updated.
Please report to me why now this behavior has changed.

**Comment by corradocavalli** [comment]
At the beginning load project was possible only with key and code and that is the only time i saw the "outdated message" we never invoked any sort of checking at startup so behavior hasn't changed, it always been like this.
Unclear message on project lists has been fixed in v 111.
Regarding version checking at startup, I need to know what is the API to invoke in order to implement it.

**Comment by gsantopaolo** [comment]
@corradocavalli close if fixed please

**Comment by gsantopaolo** [comment]
@tamarawasser can you please very and close if solved otherwise mark as bug and assign to dev
