### ISSUE TITLE
Deleting inking caused a Panda

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#397]
v 120
Surface Book
Project Code: 2788
Project Key: r0vda
Project description: sdfb

I inked a lot of stuff, with different pen types/colors.
I started to delete the inking. At some point, I got this error message
![image](https://user-images.githubusercontent.com/19929395/31990299-fdcf944a-b974-11e7-95ac-d00eecc9f4ec.png)

**Comment by gsantopaolo** [comment]
@corradocavalli this means you passed an inkid to delete that the db doesn't find.
maybe if it is a delete we just don't rise errors? but this scares me a it... we need to discuss it...

**Comment by corradocavalli** [comment]
@gsantopaolo We need to discuss about this because if, for any reason the same request to delete a stroke  goes to the server twice we got this message. This might happen because of SignalR retry tentative or because two usera trying to delete the same stroke at the same time (I tried and in fact it happens)

**Comment by corradocavalli** [comment]
Fixed in v 1.40.
