### ISSUE TITLE
Login Problems with some MS Accounts

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#467]
1.Download CollaBoard
2.Login with MS Account (MS employee) -->Login not possible
3.Login with Hotmail account (private) -->Login is possible. 

Do we have any chance to figure out why login with MS Account is not possible. Do we get here some data back that would allow us to investigate the issue?

**Comment by corradocavalli** [comment]
You mean something like corrado.cavalli@ibv.ch<mailto:corrado.cavalli@ibv.ch> as account right? Otherwise give me some valid credentials to use for testing

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Michael Görög<mailto:notifications@github.com>
Inviato: martedì 23 gennaio 2018 15:18
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [IBVSoftware/CollaBoard-Feedback] Login Problems (#467)


1.Download CollaBoard
2.Login with MS Account (MS employee) -->Login not possible
3.Login with Hotmail account (private) -->Login is possible.

Do we have any chance to figure out why login with MS Account is not possible. Do we get here some data back that would allow us to investigate the issue?

**Comment by mtg1986** [comment]
Yes it was an official MS company account from a key account manager. I am not sure if he can give me his credentials for testing... 
For me it would be good to know what to do in a case like that to support him or give an advise what the IT department needs to change that login is possible.

**Comment by corradocavalli** [comment]
I tried with mine and it works, can you try (or ask to) try if it is something related to that account or type of account, not much of our code is involved in authentication process.

**Comment by mtg1986** [comment]
Thanks for the info. Do you know if in Telemetry failed Log-In attempts are tracked? It would be good to know how many people have issues to log-in into CollaBoard and to figure out what the reason is why they cannot login.

**Comment by mtg1986** [comment]
Would it help, if we can arrange a Skype session with the user that has the login-issue? What info do I need the user to provide in a case like this?

**Comment by corradocavalli** [comment]
Would it be perfect if he could provide us a temporary account that we can use for testing. Can you arrange this with him?


________________________________

**Comment by mtg1986** [comment]
Ok, I will ask if it is possible.

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli what if we go to that user or if he cae to our office and we ask him to login on one of our dev device so e has not to share his credentials?

**Comment by corradocavalli** [comment]
Doable as well for me...

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli  what about this?

**Comment by corradocavalli** [comment]
On my side alli can say is that I'm waiting for a testing/reply scenario.

**Comment by mtg1986** [comment]
I will meet this guy tomorrow. What options do I have to help him? 

It would be nice to track in telemetry failed login attempts so we can quantify how often this is an issue.

**Comment by corradocavalli** [comment]
My feeling is that that specific user is not a live/Office365 account and so graph api we use for authentication fails.
Logging won't help that much because authentication process is handled internally by various providers (the MS popup as example) and the only feedback we have is whether operation succeeded or not, and this would include wrong password entering or user cancellation making stats unreliable.

**Comment by mtg1986** [comment]
I talked this week with this guy from MS and the issue was solved from his side. That means he could login. Would be interesting to know why it was not possible the first time. 
For me the big question is, how can I deliver support to someone who has this problem.

**Comment by corradocavalli** [comment]
The only thing that comes to my mind is to ask the user if account was a live/Office 365 account, I think login doesn't work with ADFS users.
Maybe @kasuken can support you on this...
Can we close this?

**Comment by mtg1986** [comment]
Closing this as the support case for the MS guy is solve.d
