### ISSUE TITLE
Connecting Tiles - Arrows are dislocated 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#485]
When connecting tiles, the arrows are not in the right position anymore. Before the were in the middel and now on the side. Please have a look at the image and the highlighted arrows.

![image](https://user-images.githubusercontent.com/19570958/35408666-473f111c-0210-11e8-8108-775b084955e6.png)

**Comment by corradocavalli** [comment]
This is a known issue since initial release...

On 25 Jan 2018, at 20:43, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When connecting tiles, the arrows are not in the right position anymore. Before the were in the middel and now on the side. Please have a look at the image and the highlighted arrows.

[image]<https://user-images.githubusercontent.com/19570958/35408666-473f111c-0210-11e8-8108-775b084955e6.png>
