### ISSUE TITLE
Locked Tiles - Enhancement Suggestion

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#511]
This is more a conceptual thing. 

Imagine two people working on a CollaBoard project. One person closes the project, alotugh not all tiles are saved. So one tile stays in edit mode. This tile is now blocked for the rest of his life by this user. It would be great to find a solution that for example to project owner can overtake this tile or that the tile is not in edit mode anymore after a certain time. 
For example: In some sample project where I am project owner, there are locked tiles by Tamara and I cannot do anything with them.

**Comment by corradocavalli** [comment]
If you close a project with some tiles still in edit mode you get a warning and if you confirm the close operation they get automatically saved and unlocked.
The issue you see happen when application unexpectedly quits (e.g. crashes) and is no longer opened by that user.
This issue is known and still pending.

On 25 Feb 2018, at 11:03, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


This is more a conceptual thing.

Imagine two people working on a CollaBoard project. One person closes the project, alotugh not all tiles are saved. So one tile stays in edit mode. This tile is now blocked for the rest of his life by this user. It would be great to find a solution that for example to project owner can overtake this tile or that the tile is not in edit mode anymore after a certain time.
For example: In some sample project where I am project owner, there are locked tiles by Tamara and I cannot do anything with them.

**Comment by gsantopaolo** [comment]
@mtg1986  for collaboard enanchement please do not use this repo, we have a lot of issue and bugs and it will be lost.
Please write it down somewhere so that we can discuss offline me and you 

thank you

**Comment by mtg1986** [comment]
Closing this as we need to discuss this in the meeting.
