### ISSUE TITLE
Lost Ink

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#524]
Worked more than one hour on a project (only on Surface Hub). 
After closing and reloading the project most of the ink was not there anymore. 
Only inked on the background. 

We will try today to figure out when it does happen and to reproduce it.
This is now the second time in one week, where I lost some ink on the background, so there must be somewhere an issue. 

Version:2.0.13

Project: 
Project Code: 13469
Project Key: corx1

**Comment by corradocavalli** [comment]
Michi,
You lost ink on background or in the tiles?
Is not clear from what you say.
Are you using wire or wifi?
To test:
1-Open the same project on two devices
2-Work on a single device and see if they come out of sync

If it happen, can you try again not using IBV network? (Maybe a tethered connection)
Looks like that SignalR connection stops working without any feedback to the app and so actions get lost resulting in lost ink or general out of sync issues we have since longtime.

On 5 Mar 2018, at 08:24, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


Worked more than one hour on a project (only on Surface Hub).
After closing and reloading the project most of the ink was not there anymore.
Only inked on the background.

We will try today to figure out when it does happen and to reproduce it.
This is now the second time in one week, where I lost some ink on the background, so there must be somewhere an issue.

Version:2.0.13

Project:
Project Code: 13469
Project Key: corx1

**Comment by mtg1986** [comment]
Hi Corrado, no just Ink on the background. Did not work with other objects in that project (as far as I remember). 

We were using the Hub on the 2nd floor, which should be connected over the wire. We will try to test today and use different internet connections.

**Comment by corradocavalli** [comment]
Probable duplicate of https://github.com/IBVSoftware/CollaBoard-Feedback/issues/463

**Comment by corradocavalli** [comment]
It should be fixed in 2.0.14

**Comment by mtg1986** [comment]
Tested and were not able to reproduce. Therefore closing.
