### ISSUE TITLE
Export - Youtube Video

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#540]
When I click on the export button of a YouTube video, I cannot export the video. 

1.Drag and Drop YouTube video 
2.Click on Export
3.I can only export a txt file
4.In the file I have a very long link 

1.Drag and Drop Youtube video
2.Ink on the video
3.Click on export with Ink 
4.Only Ink is exported and not an image or something else of the video
-->I believe this is not what a user expects. If it is not possible to export images with ink of YouTube videos or export the video itself we should remove the button "Export" on YouTube videos.

**Comment by corradocavalli** [comment]
The long link is the link to YouTube video, current implementation is the best we can do with YouTube video since is not technically possible to grab the current frame.
Said this, take a final decision on export feature for YouTube tile.

On 23 Mar 2018, at 08:10, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When I click on the export button of a YouTube video, I cannot export the video.

1.Drag and Drop YouTube video
2.Click on Export
3.I can only export a txt file
4.In the file I have a very long link

1.Drag and Drop Youtube video
2.Ink on the video
3.Click on export with Ink
4.Only Ink is exported and not an image or something else of the video
-->I believe this is not what a user expects. If it is not possible to export images with ink of YouTube videos or export the video itself we should remove the button "Export" on YouTube videos.

**Comment by mtg1986** [comment]
@gsantopaolo : What do you think, should the export button be removed from the YouTube video tile? 

Or should the text be changed from "Export Video" to "Save Video Link"?

**Comment by mtg1986** [comment]
Tested with 2.0.24. 
@gsantopaolo : Could you already think about what to do with the export button on the Youtube video tile? For me it makes no sense when it says "Export video" and then a .txt file is exported.

**Comment by gsantopaolo** [comment]
@mtg1986 for youtube video what we have is a link.
It would be possible to export the video from youtube, but it would take some time.
Two things in my mind:
1. export gives back you the original linke
2. export hidden for youtube video

you chose, my vote is for the link...

**Comment by corradocavalli** [comment]
Inside the txt file there is exactly the link to the video,
We can rename the button text with "Export video link"

**Comment by gsantopaolo** [comment]
yes, i know there is the link i was thinking to something that can be a real link, maybe html file ? let's see if @mtg1986  whats it we will change accordingly

**Comment by mtg1986** [comment]
@gsantopaolo : This sounds like a good idea having the real link. I am not sure regarding the effort, as this is low prio in my opinion.

**Comment by gsantopaolo** [comment]
@corradocavalli  can do it easily...

**Comment by corradocavalli** [comment]
Not a problem, but with an HTML file you will have a page opened by default browser pointing to youtube page or with embedded video.
Is this what we want or do we want the user to be able to have the uri of the video for his own purposes?

**Comment by mtg1986** [comment]
@corradocavalli : Can we do this solution as suggested from Gian: "export gives back you the original linke"?

**Comment by corradocavalli** [comment]
When you export a video what you have inside the .txt file is exactly the link to the video. 
If the goal is to use that link for sharing or document embedding this is the best solution IMHO.
How is this feature going to be used?

**Comment by mtg1986** [comment]
Tested with 2.0.47 on Surface Pro and Surface Hub. 
On Surface Pro it works fine, on Surface Hub the .html file cannot be loaded. From my point of view we should not continue fixing this on the Hub. I think the use case of saving a YouTube video link on the Hub is not relevant. 
Therefore I am closing this bug now.
