### ISSUE TITLE
Tile Header - Ink position and dropping to grid library

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#552]
It seems that with the new feature "remove header when not interaction with tiles", changes the position of Ink on existing sticky notes. 

See this example:
1.Create project form Sample "Mind Map"
2.Take out a sticky note from a grid library
3.See how ink is not at the same position anymore (it moves up)
4.Put Sticky Note back to grid library

-->Here we have the issue that the header now covers part of the ink. In the video you see that for one sticky note a strange black header appears. 

![image](https://user-images.githubusercontent.com/19570958/37887991-32c47950-30c5-11e8-99e4-6bfca74cc75a.png)

Link to the video: https://ibvinfo.sharepoint.com/:v:/s/mktg/EVlAP-xQrq1FkSUcb912AqYBVVk6YM2YsBb8bOVbSSn_yQ

Tested on Desktop PC
2.0.16

**Comment by corradocavalli** [comment]
The tiles inside a lib/grid library are not real tiles but a screenshot of the tile at the moment it get dropped into container. The image for this case were created before we introduced the new auto hiding toolbar, that's why when you drag them out (going to a real tile) you see that difference.
If you drop them back you will see that behavior is correct again.
Maybe we'll have to update all templates/samples when we'll go live with this new toolbar mode.
Can't reproduce the black bar status issue.

**Comment by mtg1986** [comment]
Tested with 2.0.21. Was not able to reproduce the black bar. Now the experience is much better, as user does not get the impression that ink is moving when taking a sticky note out of the library. Therefore I close the bug.
Surface Hub
