### ISSUE TITLE
Collaboard not running on parallels 

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#554]
Can you assigners please update on this bug? I know @agorog  was able to reproduce it...

**Comment by corradocavalli** [comment]
I investigated on Ema's Mac book: The problem is that on Paralles even with 96 DPI settings we have the "Canvas 10000x6000 requires a bitmap bigger that 8192" as test I've tried lowering the DPI but then Parallel goes crazy showing a flashing screen.
Honestly I have no idea of how we could fix this, apart testing again when we will work on infinite canvas task.

**Comment by gsantopaolo** [comment]
@corradocavalli can you try send a mail to the mvp win dl?

**Comment by corradocavalli** [comment]
Think this will be fixed when we'll implement large canvas support.

**Comment by mtg1986** [comment]
Asked the ones who have parallels to test again.

**Comment by mtg1986** [comment]
Tested with 2.0.41 and it is working. Closing the bug now.
