### ISSUE TITLE
Start Screen Performance 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#580]
When using an account with a lot of projects, the performance of the start screen is very bad. It takes long time until the thumbnails of the proejcts are loaded. 

Tested with 2.0.22 on Surface Pro

**Comment by corradocavalli** [comment]
Did some tweaks, see #582, please try with version 2.0.23.

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
I have investigated the problem and looks like that involved API response (GetMyProjectsAsync, GetParticipatingProjecsAsync...) degrades depending on presence of project screenshots (each one is about 150 KB)
In order to mitigate the issue a bit I've reduced the page size from 50 to 10, unfortunately this will cause more 'buffering' when scrolling, give it a try.
I can prevent projects reloading when closing a project but think we need some 'refresh' button somewhere.

**Comment by mtg1986** [comment]
Thanks, tested with 2.0.24 it is much better now. Therefore I close the issue.
Tested on Surface Pro.
