### ISSUE TITLE
Tiles into Library

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#586]
If you put a new tile into a library, you need to drag it to the library, stop moving the tile and then it asks, whether you want to drop the file into the library or not, that's how it's supposed to work.
But if you don't stop moving the tile, if you just throw it to the library without purposely stopping the movement, the tile just sits on top of the library without being put in.
![library](https://user-images.githubusercontent.com/19570958/40164076-dbc6604c-59b8-11e8-882b-ca69a2722713.png)

Tested on Surface Hub and Surface Pro

Version 2.0.23.0

**Comment by corradocavalli** [comment]
If you remember confirmation request has been added to exactly prevent the "sinking" behavior we had in the past when throwing tiles along the canvas. Detecting and asking when we should ask user if he really wishes to move thrown tile into library is not something trivial.
If you see this as a important feature discuss about it so that we can plan it for future enhancement.

**Comment by gsantopaolo** [comment]
@mtg1986  that's the correct behavior from my point of view. What's your expectations?

**Comment by mtg1986** [comment]
@gsantopaolo @corradocavalli : After trying this out again (with 2.0.41) I think you are right. Therefore I will close the bug.
