### ISSUE TITLE
Connecting Tiles

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#593]
If you connect one tile to another one to the right, you see the connection between them. If you take the tile on the right and pull it to the leftside of the connected tile, so 180 degrees turn to the other side, the connection isn't visible anymore.

Also, if a tile is pinned to the canvas, you can connect FROM the pinned tile, but not from another one TO the pinned tile.

Tested on Surface Hub, Version 2.0.24

**Comment by corradocavalli** [comment]
The behavior to exclude pinned tiles to be available as target connections was by design, no idea why.
I've removed the limit in v 2.0.25, if you remember why it was like that let me know.
Regarding the rest: As you know diagram connections have several limitations, implementing a fix is not trivial, we need to discuss how special scenarios like the one mentioned should behave.

**Comment by mtg1986** [comment]
We tested the connecting feature of the pinned tiles and this is working now. Tested .with 2.0.41 on Surface Hub. Therefore we close this bug for the moment.
