### ISSUE TITLE
Store zoom level when closing project

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#78]
Version 1.3.0.0

When I close and open the project. The project will is displayed zoomed with all the tiles showing. 
Sometimes this is good but sometimes I would like to close the project having the zoom factor saved, so I can continue my work exactly where I left it, without having to try to reach the same zool level after opening the project again. Maybe as option at close or as property of the project ?

**Comment by gsantopaolo** [comment]
I agree with @agorog unfortunately CollaBoard is a shared canvas, this means that is would not be possible to save your preference. Because if you clase the project with a zoom level another user uses the same project and save his zoom level then when you open it you would get last user zoom level.
Btw i believe this is good.
So let's go that way, last users exit saves his tile poisition and zoom factor as well.

**Comment by corradocavalli** [comment]
Maybe a 'fit all when project loads' option in app settings might help?

On 29 Jan 2017, at 11:32, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree with @agorog<https://github.com/agorog> unfortunately CollaBoard is a shared canvas, this means that is would not be possible to save your preference. Because if you clase the project with a zoom level another user uses the same project and save his zoom level then when you open it you would get last user zoom level.
Btw i believe this is good.
So let's go that way, last users exit saves his tile poisition and zoom factor as well.

-

**Comment by gsantopaolo** [comment]
honestly i really do not like the zoom to fit when you hope it is very bad.
Please prepare client object, we will store the value of the zoomed board when user closes the project.

**Comment by corradocavalli** [comment]
I think this is just a value to associate with the project (like readonly) at this point i would save also the x and y offset so that we can recreate the same exact situation when the user reopen a project.
Zoom to fit offers a good canvas overview, i think it could be used as default for previously unsaves projects.
Of course these are user related properties.

On 6 Feb 2017, at 19:58, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


honestly i really do not like the zoom to fit when you hope it is very bad.
Please prepare client object, we will store the value of the zoomed board when user closes the project.

**Comment by gsantopaolo** [comment]
yes store zoom level and position on notifysuspend please

**Comment by gsantopaolo** [comment]
add machineid

**Comment by corradocavalli** [comment]
Available on v17
