### ISSUE TITLE
Project info tile rotates (but only when you create a new project)

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#79]
Hub
Time: 16.25
Date: 29/01/2017

As long as you create a new project, you get the project info message box. You can rotate this specific tile although I think this shouldn't behave like that (but, to me, it's a minor issue)

Key: 1441
Code: s1454
![wp_20170129_16_15_56_pro](https://cloud.githubusercontent.com/assets/19929395/22405243/1291bbe6-e640-11e6-9964-87a40da62db8.jpg)

**Comment by corradocavalli** [comment]
No that's a bug, system tile shouldn't rotate. Weird because it should have been fixed.

On 29 Jan 2017, at 16:29, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Hub
Time: 16.25
Date: 29/01/2017

As long as you create a new project, you get the project info message box. You can rotate this specific tile although I think this shouldn't behave like that (but, to me, it's a minor issue)

Key: 1441
Code: s1454
[wp_20170129_16_15_56_pro]<https://cloud.githubusercontent.com/assets/19929395/22405243/1291bbe6-e640-11e6-9964-87a40da62db8.jpg>

-

**Comment by corradocavalli** [comment]
Fixed
