### ISSUE TITLE
[Feedback] Style and size

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#81]
When you click on a specific pen and you want to pick a size, you need to click on that icon again to do that.
IMHO I think user has to have the possibility to open the pen menu -> pick a color AND a size -> start inking (without clicking on it twice).

**Comment by corradocavalli** [comment]
Agreed, but this complaint should be addressed to Microsoft since that's how his toolbar works.

On 29 Jan 2017, at 16:34, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


When you click on a specific pen and you want to pick a size, you need to click on that icon again to do that.
IMHO I think user has to have the possibility to open the pen menu -> pick a color AND a size -> start inking (without clicking on it twice).

-

**Comment by teguria** [comment]
ok then I'll ask them
