### ISSUE TITLE
Add Tiles Menu over multiple tiles

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#83]
HUB
17.14 29/01/2017

When you have multiple tiles and you want to add new tiles, you click on the radial menu but the "Add Tiles" menu remains behind all the other tiles you already have. I think it should pops up on top of everything

**Comment by gsantopaolo** [comment]
there is no hovering functionality when you use touch... so that's not possible... As already told on #77 this is a touch and ink designed app... we can do that but it requires time to develop things that are not the core... so we will do it only if we will have thousands of collaboard users asking for this... :)
