### ISSUE TITLE
Yes/No Buttons on Grid Library deletion request

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#87]
HP Spectre 360 laptop
09.06, 30/01/2017 v 1.3.1.0

CollaBoard is not zoomed in
Created Library, Request to delete it, Buttons YES/NO are somehow crossed
![grid](https://cloud.githubusercontent.com/assets/19929395/22416003/cd71b30e-e6cb-11e6-9112-60b708052be7.png)
Will test it again with a new project

**Comment by teguria** [comment]
I can confirm that, with a new project, the grid library, because of its size, shows up with the yes/no buttons crossed

**Comment by corradocavalli** [comment]
It's a known issue, current delete experience is not good since it relies on tile size.
I propose this alternative: when you click the delete button a panel slides from top and cover the entire toolbar, maybe with a orange background to attract attention, with text and yes/no buttons on the right.
Please discuss it or propose alternatives.

On 30 Jan 2017, at 09:11, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


I can confirm that, with a new project, the grid library, because of its size, shows up with the yes/no buttons crossed

-

**Comment by agorog** [comment]
This only happens with 2x2 grid libs, with 3x3 and more, everything is shown ok

**Comment by corradocavalli** [comment]
Yes, but the approach is not the graphically ok anyway, on a very big tile you don't see yes/no button while they should be close where you clicked (the toolbar in this case) see my previous proposal.

**Comment by gsantopaolo** [comment]
@corradocavalli  panel to slide yes, orange background no, yes and no have to be on the same line.
please use proportion

**Comment by corradocavalli** [comment]
![delete](https://cloud.githubusercontent.com/assets/5617938/22696616/fb7764f4-ed4e-11e6-8465-554ebef2cd25.gif)

UI has been refactored as in the above picture. We have to shorten German delete text though
