### ISSUE TITLE
Video recoding not working

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#95]
1.Create a new project
2.Record video for several seconds
3.Chance that it works is 50%. 
4.When it does not work, nothing happens when I press on the video camera icon to stop the recording. 

Surface Pro 4
02.02.2017 09:30
Project Code: 3449
Project Key: vb317
ibv-collaboard:open?code=3449&key=vb317

**Comment by corradocavalli** [comment]
"several" means how many seconds, is that recurrent and happens on different devices?

**Comment by gsantopaolo** [comment]
@mtg1986  4 days no action

**Comment by mtg1986** [comment]
was not able to reproduce

**Comment by agorog** [comment]
1.3.10.0 Project 3813 / 0gc6n   10.02.2017 17:05 
On Surface Pro 4: Add Camera / Video < 5s. all ok.  If recording is longer then 5 s nothing happens. Dont know if recorded video is to big (10MB limit upload?) 
On Hub: Recorded 14s ok. recorded 30s ok. 35s ok, 40s nothing happens.

**Comment by mtg1986** [comment]
Video recording on device with no camera

1.When clicking on the camera icon, immediately the error message appears: 
![image](https://cloud.githubusercontent.com/assets/19570958/22873025/851b3ed4-f1bd-11e6-81d3-186f7673a31a.png)
2.Project closes 

Testes on: 
Version 1.3.10.0
Device: HP Desktop PC (without audio and video recording possibilities)

**Comment by corradocavalli** [comment]
The new version will include a check that will show this dialog in case no camera are present into system. Please test it when next release will be out since I don't have any machine w/o camera for doing some dev tests,
![image](https://cloud.githubusercontent.com/assets/5617938/22877773/3fba8d94-f1d7-11e6-934c-ade47f1a9c0a.png)

**Comment by agorog** [comment]
Tested with 1.3.41.0 , if the Video is too big nothing happens: 
Project Code: 1779
Project Key: 3ddnq
Project description: Test video length
ibv-collaboard:open?code=1779&key=3ddnq

On Surface Pro 4: 

Add Camera tile, Record and wait until recording max time is over, Camera is still here, you close nothing happens. 
Do same with short video less then 12 seconds, everything ok. 

Dont know if the problem is really the size, but I assume. User should get a message, that tile cannot be stored or even better, recording should not allow to record more then max file upload size

**Comment by corradocavalli** [comment]
Fixed, now a message appears when file size is too big.
